name = "muna-bhattarai-portfolio"
compatibility_date = "2024-08-31"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "out"

[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "directory"
dir = "out"

[env.production]
name = "muna-bhattarai-portfolio"

[env.production.vars]
ENVIRONMENT = "production"
NODE_VERSION = "20"

# Custom domain configuration
[[env.production.routes]]
pattern = "munabhattarai.com.np"

[[env.production.routes]]
pattern = "www.munabhattarai.com.np"
