name: Simple Cloudflare Deploy

on:
  workflow_dispatch: # Manual trigger
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - '.github/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: List output directory
        run: ls -la out/

      - name: Deploy to Cloudflare Pages
        run: |
          npm install -g wrangler
          npx wrangler pages project create muna-bhattarai-portfolio --production-branch main || echo "Project already exists"
          npx wrangler pages deploy out --project-name=muna-bhattarai-portfolio
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
