name: Deploy Portfolio to Cloudflare Pages

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '*.md'
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_dispatch: # Manual trigger
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - preview

jobs:
  # Build job (shared by both production and preview)
  build:
    runs-on: ubuntu-latest
    name: Build Application
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js application
        run: npm run build
        env:
          NODE_ENV: production
          CI: true

      - name: List build output (for debugging)
        run: ls -la out/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: out/
          retention-days: 1

  # Production deployment (main branch only)
  deploy-production:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    name: Deploy to Production
    environment: production
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: out/

      - name: Install Wrangler CLI
        run: npm install -g wrangler@3.80.0

      - name: Deploy to Cloudflare Pages (Production)
        run: npx wrangler pages deploy out --project-name=muna-bhattarai-portfolio
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Production deployment success notification
        run: |
          echo "🚀 Production deployment completed successfully!"
          echo "Live at: https://munabhattarai.com.np"
          echo "Cloudflare URL: https://muna-bhattarai-portfolio.pages.dev"

  # Preview deployment (pull requests only)
  deploy-preview:
    if: github.event_name == 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    name: Deploy Preview
    environment: preview
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: out/

      - name: Install Wrangler CLI
        run: npm install -g wrangler@3.80.0

      - name: Deploy Preview to Cloudflare Pages
        run: npx wrangler pages deploy out --project-name=muna-bhattarai-portfolio
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Comment Preview URL on PR
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const prNumber = context.issue.number;
            const previewUrl = `https://${prNumber}.muna-bhattarai-portfolio.pages.dev`;
            
            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🚀 Preview Deployment Ready!
              
              ✅ **Your changes are live at:** ${previewUrl}
              
              🔗 **Links:**
              - Preview: ${previewUrl}
              - Production: https://munabhattarai.com.np
              
              📋 **Build Info:**
              - Commit: \`${context.sha.substring(0, 7)}\`
              - Branch: \`${context.ref.replace('refs/heads/', '')}\`
              
              *This preview will be updated automatically with every push to this PR.*`
            });

  # Manual deployment job
  deploy-manual:
    if: github.event_name == 'workflow_dispatch'
    needs: build
    runs-on: ubuntu-latest
    name: Manual Deployment
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: out/

      - name: Install Wrangler CLI
        run: npm install -g wrangler@3.80.0

      - name: Deploy to Cloudflare Pages (Manual)
        run: npx wrangler pages deploy out --project-name=muna-bhattarai-portfolio
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Manual deployment notification
        run: |
          echo "🎯 Manual deployment completed!"
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Triggered by: ${{ github.actor }}"
